# Install 

In [25]:
pip install pprint3x

1959.18s - pydevd: Sending message related to process being replaced timed-out after 5 seconds



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip3.10 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install requests

SyntaxError: invalid syntax (3267125407.py, line 1)

# API ЯЗЖ

# SWAGGER
https://hack-it.yazzh.ru
https://hack-it.yazzh.ru/redoc

# Получение необходимой информации по адресу/координатам (сваггер)
https://geo.hack-it.yazzh.ru/
https://geo.hack-it.yazzh.ru/redoc

In [27]:
import requests
from pprint3x import pprint
response = requests.get("https://geo.hack-it.yazzh.ru/api/v2/geo/buildings/search/", params={"query":"Аптекарский проспект 18"}).json()
pprint(response)


{'data': [{'fias_id': None,
           'full_address': 'г.Санкт-Петербург, Аптекарский проспект, дом 18, '
                           'литера А',
           'id': 209676,
           'latitude': 59.974953,
           'longitude': 30.3193827,
           'type': None},
          {'fias_id': None,
           'full_address': 'г.Санкт-Петербург, Троицкий проспект, дом 18, '
                           'литера А',
           'id': 63945,
           'latitude': 59.9156319,
           'longitude': 30.2985272,
           'type': None},
          {'fias_id': None,
           'full_address': 'г.Санкт-Петербург, Лермонтовский проспект, дом 18, '
                           'литера А',
           'id': 88206,
           'latitude': 59.9190417,
           'longitude': 30.2960033,
           'type': None},
          {'fias_id': None,
           'full_address': 'г.Санкт-Петербург, проспект Пятилеток, дом 18, '
                           'корпус 1, литера А',
           'id': 87924,
           'latitude':

по адресу получили идентификатор дома (id) 209676, а также его координаты latitude': 59.9156319, 'longitude': 30.2985272
получаем информацию по дому

In [28]:
response = requests.get("https://geo.hack-it.yazzh.ru/api/v2/geo/buildings/209676").json()
pprint(response)

{'data': {'district': {'id': 13,
                       'name': 'Петроградский',
                       'vkgroup': 'https://vk.com/petropressa'},
          'fias_id': '41c0c387-db06-4bd1-8a1a-95b88a4357bd',
          'full_address': 'г.Санкт-Петербург, Аптекарский проспект, дом 18, '
                          'литера А',
          'house': '18',
          'id': 209676,
          'juridical_address': '194354, САНКТ-ПЕТЕРБУРГ Г, УЧЕБНЫЙ ПЕР, 12, 1',
          'latitude': 59.974953,
          'liter': 'А',
          'longitude': 30.3193827,
          'managementcompany_id': 3365,
          'municipality': {'MO_short_name': 'Аптекарский остров',
                           'VK_society': 'https://vk.com/maapteka',
                           'id': 61,
                           'name': 'муниципальный округ Аптекарский остров'},
          'organization_email': 'info@ks-spb.ru',
          'organization_full_name': 'Общество с ограниченной ответственностью '
                                    '

по идентификатору дома получили наименование района (district): 'name': 'Петроградский'
делаем запрос по Афише событий: обратите на формат даты.
Для всех методов с swagger есть подробное описание query params

In [29]:

response = requests.get("https://hack-it.yazzh.ru/afisha/all/?start_date=2024-11-25T09%3A24%3A43&end_date=2025-11-25T09%3A24%3A43&location_latitude=59.9156319&location_longitude=30.2985272&location_radius=1&page=1&count=10").json()
pprint(response)

{'count': 151,
 'data': [{'place': {'address': 'Санкт-Петербург, наб. р. Фонтанки, д. 44 (1-й '
                                'этаж, Медиахолл)',
                     'age': 16,
                     'categories': ['Обучающее занятие'],
                     'coordinates': [59.915016, 30.289799],
                     'description': 'Всё, что мы знаем о рождественских '
                                    'традициях, пришло оттуда, из '
                                    'викторианской Англии. Мы, кстати, не так '
                                    'уж сильно отличаемся от её обитателей. Но '
                                    'некоторые факты вас обязательно удивят.  '
                                    'Что такое уосель? Где поговорить с '
                                    'животными в рождественскую ночь? Как '
                                    'выиграть живого енота? Кто не разрешил '
                                    'Санта-Клаусу поздравлять Скарлетт О’Хара? '
          

# API Petesburg.ru

для получения доступа к данным портала "Экосистемы городских сервисов", необходимо пройти регистрацию и в меню разработчика получить токен.
Например, чтобы получить данные по Соощениям ЖКХ, необходимо ознакомиться со swagger (https://petersburg.ru/mainPortal/api_services/view/2216)

In [ ]:
headers = {"Authorization": "Bearer <<token>>"}
response = requests.get('https://our-spb.gate.petersburg.ru/api/v2/problems/by_buildings/209676?format=miniapp&count_on_page=10', headers=headers).json()
print(response)


{'success': True, 'count': 140, 'data': [{'id': 6413903, 'reason': 'Ненадлежащее состояние малых архитектурных форм, уличной мебели и хозяйственно-бытового оборудования, необходимого для благоустройства территории', 'latitude': 59.974342, 'longitude': 30.318493, 'district': {'id': 7, 'name': 'Петроградский', 'is_updated': 1, 'is_actual': 1}, 'is_closed': 0, 'created_at': '2024-11-16 09:43:12', 'is_public': 1, 'expected_answer_dt': '2024-12-09 23:59:59', 'is_deleted': 0, 'updated_at': '2024-11-16 15:22:04', 'nearest_building_id': 209676, 'nearest_building': {'id': 209676, 'prefix': {'id': 5164, 'town_id': 36, 'geonim': {'id': 1456, 'name': 'Аптекарский проспект', 'short_name': 'Аптекарский пр.', 'only_name': 'Аптекарский'}, 'name': 'г.Санкт-Петербург, Аптекарский проспект', 'short_name': 'г.Санкт-Петербург, Аптекарский пр.'}, 'district': {'id': 7, 'name': 'Петроградский', 'is_updated': 1, 'is_actual': 1}, 'house': '18', 'liter': 'А', 'full_address': 'г.Санкт-Петербург, Аптекарский просп